apiVersion: v1
kind: Secret
metadata:
  name: device-registration-api-secrets
  labels:
    {{- include "device-registration-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  # PostgreSQL connection string
  DB_HOST: {{ include "device-registration-api.fullname" . }}-postgresql
  DB_PORT: "5432"
  DB_NAME: {{ .Values.postgresql.auth.database | quote }}
  DB_USER: {{ .Values.postgresql.auth.username | quote }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
